app:
  name: "web_app"
  mode: "dev"
  port: 8080
  start_time: "2022-05-19"
  machine_id: 1
  token_expiration: 60 # jwt token 过期时间，单位 分钟

log:
  level: "debug"
  filename: "./log/web_app.log"
  max_size: 1
  max_age: 30
  max_backups: 10

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  database: "keyshare"
  maxOpenConns: 200
  maxIdleConns: 50

redis: 
  host: "localhost"
  port: 6379 
  password: "123456"
  db: 0
  poolSize: 100

eth:
  ethclient: "HTTP://127.0.0.1:7545"
  contract: "0xDB1C25C927e6A34b17E812871CA2F25483dCAdbD"
  privateKey: "fc803dccc18bf7fd88fbe3ed007293f84233571e83d35cb8329b23a2941fcf5b"
  keystore_name: ""
  give_eth: true
  give_num: 10  # ETH
  
email:
  from_email: "youngsudotest@163.com"
  pass_word: "YZUOSPJUOSQUZFJJ"
  em_client: "smtp.163.com" # 邮件服务器地址
  em_port: 25  # 端口号